const MoleculeDatabase = {
    // Purple
    "C12H10N": {    
        "name": "c12h10n",
        "imagePath": "src/assets/C12H10N.png",
        "color": "purple",
        "weight": 1.3,
        "light_absorption": 8,
        "lifespan": 0.8,
        "bandgap": 4.5,
        "rank": 0,
        "isCorrectChoice": true,
    },
    "C14H14N": {
        "name": "c14h14n",
        "imagePath": "src/assets/C14H14N.png",
        "color": "purple",
        "weight": 5.6,
        "light_absorption": 4.5,
        "lifespan": 5,
        "bandgap": 5.7,
        "rank": 1,
        "isCorrectChoice": true,
    },
    "C20H12N": {
        "name": "c20h12n",
        "imagePath": "src/assets/C20H12N.png",
        "color": "purple",
        "weight": 3.5,
        "light_absorption": 10,
        "lifespan": 0.2,
        "rank": 1,
        "isCorrectChoice": false,
    },
    "C12H8N": {
        "name": "c12h8n",
        "imagePath": "src/assets/C12H8N.png",
        "color": "purple",
        "weight": 6,
        "light_absorption": 4.5,
        "lifespan": 4.5,
        "bandgap": 8.7,
        "rank": 2,
        "isCorrectChoice": true,
    },
    "panda": {
        "name": "pandaCompound",
        "imagePath": "src/assets/panda.png",
        "color": "purple",
        "weight": 5.7,
        "light_absorption": 2.1,
        "lifespan": 10,
        "bandgap": 8.7,
        "rank": 2,
        "isCorrectChoice": false,
    },
    //TODO: ANOTHER ONE
    // GREEN
    "C6H3F": {
        "name": "c6h3f",
        "imagePath": "src/assets/C6H3F.png",
        "color": "green",
        "weight": 2.6,
        "light_absorption": 5.8,
        "lifespan": 3.4,
        "bandgap": 3.6,
        "rank": 0,
        "isCorrectChoice": true,
    },
    "C10H6": {
        "name": "c10h6",
        "imagePath": "src/assets/C10H6.png",
        "color": "green",
        "weight": 6.8,
        "light_absorption": 8,
        "lifespan": 4,
        "bandgap": 6.4,
        "rank": 1,
        "isCorrectChoice": true,
    },
    "C8H6": {
        "name": "c8h6",
        "imagePath": "src/assets/C8H6.png",
        "color": "green",
        "weight": 3.9,
        "light_absorption": 1.0,
        "lifespan": 4.0,
        "bandgap": 6.5,
        "rank": 1,
        "isCorrectChoice": false,
    },
    "C6H4": {
        "name": "c6h4",
        "imagePath": "src/assets/C6H4.png",
        "color": "green",
        "weight": 4.1,
        "light_absorption": 5.5,
        "lifespan": 5.5,
        "bandgap": 7.9,
        "rank": 2,
        "isCorrectChoice": false,
    },
    "fox": {
        "name": "pandaCompound",
        "imagePath": "src/assets/fox.png",
        "color": "green",
        "weight": 5.7,
        "light_absorption": 6.8,
        "lifespan": 6.8,
        "bandgap": 8.7,
        "rank": 2,
        "isCorrectChoice": true,
    },
    // TODO Another one
    // BLUE
    "C6H4NO2": {
        "name": "c6h4no2",
        "imagePath": "src/assets/C6H4NO2.png",
        "color": "blue",
        "weight": 4.6,
        "light_absorption": 3.4,
        "lifespan": 2.1,
        "bandgap": 4.5,
        "rank": 0,
        "isCorrectChoice": true,
    }, 
    "C4H3S": {
        "name": "c4h3s",
        "imagePath": "src/assets/C4H3S.png",
        "color": "blue",
        "weight": 7.9,
        "light_absorption": 4.4,
        "lifespan": 2.1,
        "bandgap": 5.6,
        "rank": 1,
        "isCorrectChoice": true,
    },
    "C7H4N": {
        "name": "c7h4n",
        "imagePath": "src/assets/C7H4N.png",
        "color": "blue",
        "weight": 10.0,
        "light_absorption": 4.3,
        "lifespan": 2.1,
        "bandgap": 6.8,
        "rank": 1,
        "isCorrectChoice": false,
    },
    "C4H3N2": {
        "name": "c4h3n2",
        "imagePath": "src/assets/C4H3N2.png",
        "color": "blue",
        "weight": 3.4,
        "light_absorption": 3.2,
        "lifespan": 6.8,
        "bandgap": 8.1,
        "rank": 2,
        "isCorrectChoice": true,
    },
    "lizard": {
        "name": "lizardCompound",
        "imagePath": "src/assets/lizard.png",
        "color": "blue",
        "weight": 5.7,
        "light_absorption": 0,
        "lifespan": 10,
        "bandgap": 8.7,
        "rank": 2,
        "isCorrectChoice": false,
    },
    // TODO: another one
};

export default MoleculeDatabase;